### ISSUE TITLE
Support for opencms version 7.5.2

### ISSUE THREAD

**Issue by maniankara** [alkacon/opencms-docker#1]
Hi there,
  First of all good work guys !
This is not a bug, its a new feature requesting to provide docker image for opencms_7.5.2.
I know this is a bit of stretching, if you guys are willing to accept my pull request, then I can do it from my end and send them.

Thanks for understanding,
- Anoop

**Comment by aKandzior** [comment]
Anoop, thanks for offering support for OpenCms on docker. However, OpenCms 7.x does not support automatic installation without user interaction, this feature was added in 8.x. I believe offering a Dockerfile based setup for OpenCms 7 will not be possible.
