### ISSUE TITLE
opencms 11-beta 2 fails to startup

### ISSUE THREAD

**Issue by ggiudetti** [alkacon/opencms-docker#10]
Just tried to run the new beta 2 image, but it fails to update a configuration and shuts down (or at least the wizard remains enabled).
 
[docker-compose.txt](https://github.com/alkacon/opencms-docker/files/2918733/docker-compose.txt)

**Comment by tHerrmann** [comment]
Hi,
are you trying to update an previously existing OpenCms installation?

**Comment by ggiudetti** [comment]
no, cleaned up all images first

**Comment by tHerrmann** [comment]
My question was a bit misleading. Are you mounting the webapps folder from your host system with an preexisting OpenCms installation?

**Comment by ggiudetti** [comment]
That was the problem, thanks. Tried on a newly installed machine and it's working flawlessly!
