### ISSUE TITLE
alkacon/opencms-docker:11.0.0-rc - no default modules appear

### ISSUE THREAD

**Issue by tomwolfgang** [alkacon/opencms-docker#11]
I ran the alkacon/opencms-docker:11.0.0-rc container and then entered the setup phase.
When I had to select which module to install - an empty list appeared.
I tried to restart/removed the image and reinstalled it - nothing helped.

I ended up entering the container's terminal and manually downloading the zip from your site and inflated the war file manually in the webapps directory - this solved my issue.

Thanks

**Comment by tHerrmann** [comment]
Using the opencms-docker container you are not supposed to run the setup manually. When first starting the container the setup is run automatically, installing the components 'OpenCms Workplace' and 'Alkacon OpenCms Demo Template' by default. You can override the components to install by setting the environment variable 'OPENCMS_COMPONENTS' providing a comma separated list of components.
The components available are 'workplace', 'demo' and 'legacy'.
You can monitor the automatic setup process by viewing the docker log of the OpenCms container.

**Comment by tomwolfgang** [comment]
Ok, thanks
