### ISSUE TITLE
Timeout while trying to connect to database

### ISSUE THREAD

**Issue by ManfredSchenk** [alkacon/opencms-docker#19]
Environment: 
- debian stable within WSL2 inside Windows 10 Pro 22H2
- OpenCms 14 image
- docker-compose file from github (only passwords changed)

Problem:
Operation timeout: database not accessible

![grafik](https://user-images.githubusercontent.com/14162528/201643502-1abc4974-81f2-4965-8e9a-950317cd75ad.png)

**Comment by alkacon-jGraf** [comment]
It seems that you do not start with a fresh MariaDB. Please remove the container as well as the mounted folder and try again. In the directory of the docker-compose.yml file:

docker-compose stop opencms
docker-compose rm -s mariadb
rm -rf ~/dockermount/opencms-docker-mysql
docker-compose up -d

**Comment by ManfredSchenk** [comment]
same behaviour after removing container and folder...
![grafik](https://user-images.githubusercontent.com/14162528/201656456-0ad87391-e52a-4c6d-b739-9a8ae92aff1d.png)

**Comment by alkacon-jGraf** [comment]
This is a problem related to your virtual machine: "failed with ENOMEM". Closing this issue.

**Comment by ManfredSchenk** [comment]
seems to be a common problem with latest mariadb images when running inside docker in a non-ubuntu environment. managed to start mariadb now by downgrading mariadb to 10.7.7-focal. But still timeout from opencms.
