### ISSUE TITLE
OpenCms is not properly initialized!

### ISSUE THREAD

**Issue by Thlenzi** [alkacon/opencms-docker#22]
Hi everyone!

I'm a fresh on this CMS. I justo install the image from Docker.

Every process was gone well by the docker logs. 

But, i'm getting the follow error when i try to open in the browser:

HTTP Status 404
OpenCms is not properly initialized!
Please make sure that the OpenCms setup wizard has been run once and is disabled now.
The requested resource [/] is not available

How can i sove that error?

**Comment by alkacon-jGraf** [comment]
We could not reproduce the issue. Please note the following in the README:

> On the other hand, if you like to start with a completely fresh OpenCms installation, do not forget to delete both mounted directories before.

Please try once again with deleted directories.
