### ISSUE TITLE
Multi-site configuration not working

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-docker#7]
Just after configuring an additional site, the workplace displays a connection error.

Opening the quick-launch menu also displays a misbehaviour (missing icons, server incorrectly configured warning).

![screenshot_2017-10-25_14-34-23](https://user-images.githubusercontent.com/790448/31999116-7928615e-b992-11e7-8dbe-82325d94fd90.png)

The workplace is also missing:

![screenshot_2017-10-25_14-34-59](https://user-images.githubusercontent.com/790448/31999126-8418cc0c-b992-11e7-826f-9ce64fa310bf.png)

## How to reproduce

1. Create the docker container based on the opencms-docker image and assign it at least two IP addresses:
```
root@cf6bf5118ce6:/# ip -4 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
37: eth2@if38: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 192.168.0.6/30 scope global eth2
       valid_lft forever preferred_lft forever
39: eth1@if40: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 192.168.0.10/30 scope global eth1
       valid_lft forever preferred_lft forever
41: eth0@if42: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 192.168.0.2/30 scope global eth0
       valid_lft forever preferred_lft forever

```
2. Start the container
3. In the opencms workplace -> Launchpad -> Site Management. The only configured site in the official docker image is localhost:

![screenshot_2017-10-25_17-16-52](https://user-images.githubusercontent.com/790448/32006912-51dab23a-b9a8-11e7-8ac3-3296ef53aefc.png)

4. Create new site: Site actions -> New site. E.g.:
![screenshot_2017-10-25_17-24-09](https://user-images.githubusercontent.com/790448/32007247-542772c0-b9a9-11e7-8a7d-9918613a3743.png)

5. Wait a few seconds. The first symptom emerges ("Connection to server lost..."):
![screenshot_2017-10-25_17-24-38](https://user-images.githubusercontent.com/790448/32007298-743d6060-b9a9-11e7-911c-235c2ae897c8.png)

**Comment by aKandzior** [comment]
This is the expected behaviour. 

The reason is that the workplace server is not accessed through the configured ip address or server name. This is ignored as long as there is only one site configured. As soon as there is more than one site configured, all access to the workplace must be using the configured workplace server url.

**Comment by gallardo** [comment]
Thanks a lot! 👏 

Indeed:
![screenshot_2017-10-25_21-43-47](https://user-images.githubusercontent.com/790448/32019477-a646c672-b9cd-11e7-80a1-f65a135ec4f4.png)

**Comment by D612** [comment]
Same problem in OpenCms 11.0.1. Don´t site Manager in OpenCms 11.0.1. -_-'

**Comment by aKandzior** [comment]
The problem is with your configuration. Ti disable the message, fix the configuration. 

The workplace server is apparently not accessed through the configured ip address or server name. This is ignored as long as there is only one site configured. As soon as there is more than one site configured, all access to the workplace must be using the configured workplace server url.

**Comment by D612** [comment]
> Please delete. Issue no longer exists. Solved

Dear chriskuku,

I didn't understand your request to remove this thread from the problem that was reported in 2017 by a user and also by me in 2019.

The problem actually existed/exists and for reasons of history and configuration management, it is important that this thread is maintained.

It makes no sense to me that you would make this type of request.

**Comment by chriskuku** [comment]
Sorry, I didn't refer to the original problem, when saying it no longer exists. This might have been misunderstanable.  I referred to the problem I posted which may have had a different cause. Please ignore my post. I just wanted to delete it, because my problem was different.
