### ISSUE TITLE
opencms 11-beta docker image 

### ISSUE THREAD

**Issue by ssklavos-ed** [alkacon/opencms-docker#8]
Is that possible to provide an opencms 11-beta docker image ?

**Comment by dSeidel** [comment]
We work on it at the moment. It'll probably be there in the next days.

**Comment by ssklavos-ed** [comment]
Thank you very much for the instant reply. Would that be easy to attach until then a screenshot of the new workplace as an indication of what to expect?

**Comment by tHerrmann** [comment]
The new docker image providing OpenCms 11.0 beta 2 is now available.
